### ISSUE TITLE
Option for making files permanent with Permanent="yes"

### ISSUE THREAD

**Issue by cameroncros** [Wintellect/Paraffin#15]
Is it possible to have the option to make all files permanent by adding the Permanent="yes" tags to all the components? 

If this is likely to be accepted, I am happy to write it up myself and submit a pull request

**Comment by JohnWintellect** [comment]
Sure. Write the code and ensure that when updating fragments this case works. Thanks!

**Comment by cameroncros** [comment]
Hello, I wrote up the code a while ago, and it was working, but I no longer work for the company or have access to the code. I might rewrite the code and try submit it sometime in the future, but can't promise anything. Probably best to close this request.
