### ISSUE TITLE
How to deal with libraries comming from nugets in different projects

### ISSUE THREAD

**Issue by omatrot** [Wintellect/Paraffin#19]
I have the following problem.
I need to install, in the same target directory, a bunch of project outputs coming from Nugets installed in several VS projects.

I used Paraffin to generate a .wxs file for each project output.
Then I added a reference to each component group in the main .wxs file.

At compile time, I have the following error, in this case with the Newtonsoft.Json library:

Error	176	ICE30: The target file 'xowlw3w9.xml|Newtonsoft.Json.xml' is installed in '[TARGETDIR]\bla\' by two different components on an LFN system: 'comp_4EBFB24CB01B40B3B5E1D2117246A5EC' and 'comp_F28FDFC3F35B442681E0E33172052746'. This breaks component reference counting.

It seems that a new GUID is used each time the initial file is created with Paraffin.
Would it be a good idea to always use the GUID embedded in the library that is used to match a corresponding symbol file ?

**Comment by JohnWintellect** [comment]
Hi omatrot. I apologize, I'm not really sure what you are asking. Are you trying to install the same file twice into the same location?

**Comment by omatrot** [comment]
The result of what I'm doing is, indeed, that the same file is installed several times in the same directory. I've solved the problem by telling Paraffin to use a subdirectory for each VS project.

Now the question that came to my mind was, for PE format files, to modify Paraffin to use the embedded GUID instead of generate a new one for the component Id/guid.

**Comment by JohnWintellect** [comment]
1. Yes, if you try to install the same file from multiple places in the installer, Windows Installer hates that. :grimacing: 

2. That wouldn't work. The GUID in the PE file is **different** on every build. The way Windows Installer wants to work is keeping the GUID associated with a particular file name as a constant. Windows installer is extremely picky about things and when you try to bend it to your will, very, very bad things happen. I'm not saying WI took the right approach, but it is the reality of life.
