### ISSUE TITLE
-update incorrect if directory tree includes subfolders with the same name

### ISSUE THREAD

**Issue by WacomKev** [Wintellect/Paraffin#20]
Paraffin version 3.13.1

Doing an update for a wxs file generated for a directory with subdirectories similar to the following:
 Help 
 +--help
 |   +--images
 +--images

Id for the <Directory> element for the second "images" folder gets set to the Id of the fist (resulting in a LGHT0091 Duplicate symbol error in WiX).

**Comment by JohnWintellect** [comment]
Get the latest 3.6 version. I solved this issue by making the directory Id's GUIDS.
