### ISSUE TITLE
-update defaults to Wix4

### ISSUE THREAD

**Issue by Towmeykaw** [Wintellect/Paraffin#21]
Hi and thanks for an awesome tool.
I just started playing with it and found an issue with the Wix4 flag with update. 
```csharp
var wix4Usage = options.Descendants(WIX4);
if (wix4Usage.Count()==1)
    {
        argValues.WiX4 = true;
    }
```
This will be true since the option is set as `<WiX4>false</WiX4>` in the wxs file CommandLineOptions

**Comment by JohnWintellect** [comment]
Thanks for the bug report (and sorry for the delay). This is all fixed now.

**Comment by Towmeykaw** [comment]
Awesome 👍
