### ISSUE TITLE
Upload to NuGet.org

### ISSUE THREAD

**Issue by lunarcloud** [Wintellect/Paraffin#26]
Would help to be able to include Paraffin in the project via NuGet package from NuGet.org - so one doesn't need to install the utility on build nodes.

Would be a simple "tools" package, like https://www.nuget.org/packages/NuGet.CommandLine - a nuspec something like...
```xml
<?xml version="1.0" encoding="utf-8"?>
<package  xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata minClientVersion="3.3">
    <id>Wintellect.Paraffin</id>
    <title>Paraffin</title>
    <description>Making WiX Easier.</description>
    <version>3.7.1</version>
    <authors>Wintillect</authors>
    <copyright>Copyright © Wintillect</copyright>
    <releaseNotes></releaseNotes>
    <tags></tags>
    <license  type="expression">CPL-1.0</license>
  </metadata>
  <files>
    <file src="Release\*" target="tools"  />
  </files>
</package>
````

and running 'nuget pack' on the nuspec.

What this does is unpack and make the files available on the PATH during the build process.

**Comment by JayToltTech** [comment]
@lunarcloud doesn't look like this repository has been touched since summer of 2017, so I'd suggest if you want this in NuGet you take a branch and publish it yourself.

**Comment by JohnWintellect** [comment]
@lunarcloud @JayToltTech I've long since retired so there won't be any updates. If anyone wants to take over the project, I'm happy to do whatever is needed to make the transition.

**Comment by JayToltTech** [comment]
That's fine.  If @JohnWintellect transfers this over to me, I'll gladly take a PR and then set things up to get it published into NuGet.

**Comment by lunarcloud** [comment]
No longer necessary now that We've moved to Wix 4 with it's NuGet packages
